In [1]:
import pandas as pd
import numpy as np

df_tasks = pd.read_csv('GlobusComputeDataset-v1-tasks.csv')
df_endpoints = pd.read_csv('GlobusComputeDataset-v1-endpoints.csv')
df_functions = pd.read_csv('GlobusComputeDataset-v1-functions.csv')

In [3]:
df_functions

,function_uuid,function_body_uuid,loc,cyc_complexity,num_of_imports
0,6f761b2f-b776-b1e2-ddeb-9ec002e484e4,1cd2079c-72a4-089e-9652-2ca5f5f9ec42,54.0,10.0,1.0
1,fef43cc0-a26a-b13f-e956-3455b3d24a41,1627f3ca-0405-4404-4dbc-bd387425aa38,3.0,1.0,0.0
2,fdecf895-cfa5-a1e8-569e-f631c60965e2,1cd2079c-72a4-089e-9652-2ca5f5f9ec42,54.0,10.0,1.0
3,cacfa841-7210-e4e8-6508-5c025381a5bd,1cd2079c-72a4-089e-9652-2ca5f5f9ec42,54.0,10.0,1.0
4,14babd79-1054-93e1-c559-713fda85fb20,44c9883f-b632-30cd-2a0e-999ff52f40c5,NaN,NaN,NaN
...,...,...,...,...,...
277381,cb97304f-5dff-e934-44d8-42144263ee2c,7502ac21-fb80-6404-5e59-7977d4b5ef7f,5.0,1.0,2.0
277382,c00910a2-0320-d35d-35c7-d3776d6b3dee,157d4850-88b8-a2bd-0914-b055d6c245fd,18.0,4.0,3.0
277383,694daf13-bf49-7aff-4d2d-0bc5e62a798a,9047fa88-a231-8867-17d1-38b787d18751,15.0,3.0,2.0
277384,5ceca064-e135-1a1f-c0e4-9ea9dab4fbd4,147e2ff0-73cb-e11d-3720-7d7a10f45f12,49.0,5.0,4.0
277385,1be0377a-ee57-a517-6319-4daad02cc1ea,9c71cc30-9211-41e5-fc52-281337604086,10.0,1.0,2.0

In [2]:
df_endpoints

                            endpoint_uuid  endpoint_type endpoint_version
0    9ad2901c-bbde-10df-3d82-066b04652b72  LocalProvider            2.0.1
1    a987a378-c136-63bb-b233-123e4364dfc5  SlurmProvider           1.0.11
2    0d942a46-ce41-4e68-9317-f195f5cb71b2  SlurmProvider           1.0.11
3    7fd56680-9238-3dd8-de0a-fcc807ae8005            NaN            2.2.1
4    b24aa0f8-d9bf-8d6f-bf19-4b41ec9bd868  LocalProvider            2.0.3
..                                    ...            ...              ...
575  e7d13838-cdb5-211a-fc7e-0c24db8d0685            NaN              NaN
576  01531522-a979-f7d6-1a55-cf35a8943053  LocalProvider            2.0.3
577  2b2a700d-662f-c4c9-508f-6cd791e1361a            NaN              NaN
578  e0dd097e-7d94-ad6e-05f2-16ddb1347e00  LocalProvider            2.0.1
579  47b028d8-11c0-23b7-3759-f59545eab181  LocalProvider            2.0.1

[580 rows x 3 columns]

In [38]:
df_tasks

,task_uuid,function_uuid,endpoint_uuid,anonymized_user_uuid,argument_size,received,waiting_for_nodes,waiting_for_launch,execution_start,execution_end,result_received
0,0ebb4c18-5d2c-4804-4329-17725d94788d,fef43cc0-a26a-b13f-e956-3455b3d24a41,651538d8-3fc4-98d6-c6a4-f89ecadd2544,def8a1a7-9bc1-e274-1213-3d6cb366d6e9,659.0,1.685553e+18,1.685553e+18,1.685553e+18,1.685553e+18,1.685553e+18,1.685553e+18
1,7162505b-ca05-99ab-6cab-66b484448980,c6e65d92-f474-2222-cba7-36d0c3b558c8,57699a1f-f727-b5ef-28db-afaffeb0cb4d,e9abae78-6295-f7c7-17de-fc5f58818a2b,6054.0,NaN,1.684329e+18,1.684329e+18,1.684329e+18,1.684329e+18,1.684329e+18
2,fd4004eb-eb9c-d3d6-b718-93cb1c91c6d9,f9fb1939-d0e5-bb44-719b-1fca97a34a8f,9b1d9849-dd78-51bb-cb47-c48ebc5ef9c9,89f2c306-4c36-ffed-2553-e86692f055c3,46.0,1.686630e+18,1.686630e+18,1.686630e+18,1.686630e+18,1.686630e+18,1.686630e+18
3,2a1e96f6-7999-b066-fc7b-e6adf8567031,eb1a35bc-eb3a-a4dd-c905-82823f30677d,9b1d9849-dd78-51bb-cb47-c48ebc5ef9c9,89f2c306-4c36-ffed-2553-e86692f055c3,46.0,1.686687e+18,1.686687e+18,1.686687e+18,1.686687e+18,1.686687e+18,1.686687e+18
4,7ee1af85-bec6-50af-50d9-0c9dfbdabcc5,b4c9f870-b439-866c-79ac-abdf5ac4b9a2,57699a1f-f727-b5ef-28db-afaffeb0cb4d,e9abae78-6295-f7c7-17de-fc5f58818a2b,11433.0,1.684338e+18,1.684338e+18,1.684338e+18,1.684338e+18,1.684338e+18,1.684338e+18
...,...,...,...,...,...,...,...,...,...,...,...
2121467,39821951-0bba-d943-4453-93f2a99868aa,82f88f19-acd6-eca1-26ba-69282730b3e0,9e9628e2-f3b2-58cc-98ab-dcef2341e1c8,d3ea41e9-5a2a-47ba-9ea4-1d404f39baad,12223.0,NaN,1.682535e+18,1.682535e+18,1.682535e+18,1.682535e+18,1.682535e+18
2121468,9a888468-ac24-1097-2eed-6e1c3c01906f,3e959bd1-f7a1-c559-981a-a54563bb1b54,9e9628e2-f3b2-58cc-98ab-dcef2341e1c8,d3ea41e9-5a2a-47ba-9ea4-1d404f39baad,196092.0,1.682534e+18,1.682534e+18,1.682534e+18,1.682534e+18,1.682534e+18,1.682534e+18
2121469,3c1578b8-2967-8a1b-8dc8-67e879060540,07cbe97e-f170-b6c2-c090-b924eb8e3c0a,9e9628e2-f3b2-58cc-98ab-dcef2341e1c8,d3ea41e9-5a2a-47ba-9ea4-1d404f39baad,50.0,NaN,1.682436e+18,1.682436e+18,1.682436e+18,1.682436e+18,1.682436e+18
2121470,9901ca42-4dc3-490b-5670-90012a8ac761,d491925e-e99e-fa6d-5c1f-70aad3bceb9f,fc1d7a40-6293-758c-2158-b7986a2089d6,d7524c22-4d1f-adba-a84b-ad7fb761b9a4,62.0,1.676524e+18,1.676524e+18,1.676524e+18,1.676524e+18,1.676524e+18,1.676524e+18
2121471,a0599a21-6668-dd5b-273d-857917b1e8fe,4a103d77-0aec-94aa-c6e3-caa0366d9ab5,c190cd2b-4574-26ed-8e1d-0c5dc84bb11f,23452a38-0dfb-233f-dde3-443d0012cc40,NaN,1.671217e+18,NaN,NaN,NaN,NaN,1.671228e+18

In [37]:
import pandas as pd

# if your DataFrame is `task_df`:
task_df = df_tasks.copy()

# convert each nanosecond epoch column to timezone-aware UTC datetime
for col in ['received', 'waiting_for_nodes', 'waiting_for_launch', 'execution_start', 'execution_end', 'result_received']:
    if col in task_df.columns:
        task_df[col + '_utc'] = pd.to_datetime(task_df[col], unit='ns', utc=True)

# verify
task_df[['received', 'waiting_for_nodes', 'waiting_for_launch', 'execution_start', 'execution_end', 'result_received']]

,received,waiting_for_nodes,waiting_for_launch,execution_start,execution_end,result_received
0,1.685553e+18,1.685553e+18,1.685553e+18,1.685553e+18,1.685553e+18,1.685553e+18
1,NaN,1.684329e+18,1.684329e+18,1.684329e+18,1.684329e+18,1.684329e+18
2,1.686630e+18,1.686630e+18,1.686630e+18,1.686630e+18,1.686630e+18,1.686630e+18
3,1.686687e+18,1.686687e+18,1.686687e+18,1.686687e+18,1.686687e+18,1.686687e+18
4,1.684338e+18,1.684338e+18,1.684338e+18,1.684338e+18,1.684338e+18,1.684338e+18
...,...,...,...,...,...,...
2121467,NaN,1.682535e+18,1.682535e+18,1.682535e+18,1.682535e+18,1.682535e+18
2121468,1.682534e+18,1.682534e+18,1.682534e+18,1.682534e+18,1.682534e+18,1.682534e+18
2121469,NaN,1.682436e+18,1.682436e+18,1.682436e+18,1.682436e+18,1.682436e+18
2121470,1.676524e+18,1.676524e+18,1.676524e+18,1.676524e+18,1.676524e+18,1.676524e+18
2121471,1.671217e+18,NaN,NaN,NaN,NaN,1.671228e+18

In [41]:
df_tasks['total_time'] = df_tasks['result_received'] - df_tasks['received']

In [42]:
df_tasks

,task_uuid,function_uuid,endpoint_uuid,anonymized_user_uuid,argument_size,received,waiting_for_nodes,waiting_for_launch,execution_start,execution_end,result_received,total_time
0,0ebb4c18-5d2c-4804-4329-17725d94788d,fef43cc0-a26a-b13f-e956-3455b3d24a41,651538d8-3fc4-98d6-c6a4-f89ecadd2544,def8a1a7-9bc1-e274-1213-3d6cb366d6e9,659.0,1.685553e+18,1.685553e+18,1.685553e+18,1.685553e+18,1.685553e+18,1.685553e+18,9.981158e+07
1,7162505b-ca05-99ab-6cab-66b484448980,c6e65d92-f474-2222-cba7-36d0c3b558c8,57699a1f-f727-b5ef-28db-afaffeb0cb4d,e9abae78-6295-f7c7-17de-fc5f58818a2b,6054.0,NaN,1.684329e+18,1.684329e+18,1.684329e+18,1.684329e+18,1.684329e+18,NaN
2,fd4004eb-eb9c-d3d6-b718-93cb1c91c6d9,f9fb1939-d0e5-bb44-719b-1fca97a34a8f,9b1d9849-dd78-51bb-cb47-c48ebc5ef9c9,89f2c306-4c36-ffed-2553-e86692f055c3,46.0,1.686630e+18,1.686630e+18,1.686630e+18,1.686630e+18,1.686630e+18,1.686630e+18,6.705731e+09
3,2a1e96f6-7999-b066-fc7b-e6adf8567031,eb1a35bc-eb3a-a4dd-c905-82823f30677d,9b1d9849-dd78-51bb-cb47-c48ebc5ef9c9,89f2c306-4c36-ffed-2553-e86692f055c3,46.0,1.686687e+18,1.686687e+18,1.686687e+18,1.686687e+18,1.686687e+18,1.686687e+18,6.464767e+09
4,7ee1af85-bec6-50af-50d9-0c9dfbdabcc5,b4c9f870-b439-866c-79ac-abdf5ac4b9a2,57699a1f-f727-b5ef-28db-afaffeb0cb4d,e9abae78-6295-f7c7-17de-fc5f58818a2b,11433.0,1.684338e+18,1.684338e+18,1.684338e+18,1.684338e+18,1.684338e+18,1.684338e+18,4.004255e+08
...,...,...,...,...,...,...,...,...,...,...,...,...
2121467,39821951-0bba-d943-4453-93f2a99868aa,82f88f19-acd6-eca1-26ba-69282730b3e0,9e9628e2-f3b2-58cc-98ab-dcef2341e1c8,d3ea41e9-5a2a-47ba-9ea4-1d404f39baad,12223.0,NaN,1.682535e+18,1.682535e+18,1.682535e+18,1.682535e+18,1.682535e+18,NaN
2121468,9a888468-ac24-1097-2eed-6e1c3c01906f,3e959bd1-f7a1-c559-981a-a54563bb1b54,9e9628e2-f3b2-58cc-98ab-dcef2341e1c8,d3ea41e9-5a2a-47ba-9ea4-1d404f39baad,196092.0,1.682534e+18,1.682534e+18,1.682534e+18,1.682534e+18,1.682534e+18,1.682534e+18,7.224264e+08
2121469,3c1578b8-2967-8a1b-8dc8-67e879060540,07cbe97e-f170-b6c2-c090-b924eb8e3c0a,9e9628e2-f3b2-58cc-98ab-dcef2341e1c8,d3ea41e9-5a2a-47ba-9ea4-1d404f39baad,50.0,NaN,1.682436e+18,1.682436e+18,1.682436e+18,1.682436e+18,1.682436e+18,NaN
2121470,9901ca42-4dc3-490b-5670-90012a8ac761,d491925e-e99e-fa6d-5c1f-70aad3bceb9f,fc1d7a40-6293-758c-2158-b7986a2089d6,d7524c22-4d1f-adba-a84b-ad7fb761b9a4,62.0,1.676524e+18,1.676524e+18,1.676524e+18,1.676524e+18,1.676524e+18,1.676524e+18,2.770294e+08
2121471,a0599a21-6668-dd5b-273d-857917b1e8fe,4a103d77-0aec-94aa-c6e3-caa0366d9ab5,c190cd2b-4574-26ed-8e1d-0c5dc84bb11f,23452a38-0dfb-233f-dde3-443d0012cc40,NaN,1.671217e+18,NaN,NaN,NaN,NaN,1.671228e+18,1.164527e+13

In [8]:
df_endpoints

                            endpoint_uuid  endpoint_type endpoint_version
0    9ad2901c-bbde-10df-3d82-066b04652b72  LocalProvider            2.0.1
1    a987a378-c136-63bb-b233-123e4364dfc5  SlurmProvider           1.0.11
2    0d942a46-ce41-4e68-9317-f195f5cb71b2  SlurmProvider           1.0.11
3    7fd56680-9238-3dd8-de0a-fcc807ae8005            NaN            2.2.1
4    b24aa0f8-d9bf-8d6f-bf19-4b41ec9bd868  LocalProvider            2.0.3
..                                    ...            ...              ...
575  e7d13838-cdb5-211a-fc7e-0c24db8d0685            NaN              NaN
576  01531522-a979-f7d6-1a55-cf35a8943053  LocalProvider            2.0.3
577  2b2a700d-662f-c4c9-508f-6cd791e1361a            NaN              NaN
578  e0dd097e-7d94-ad6e-05f2-16ddb1347e00  LocalProvider            2.0.1
579  47b028d8-11c0-23b7-3759-f59545eab181  LocalProvider            2.0.1

[580 rows x 3 columns]

In [36]:
len(df_functions['function_body_uuid'].unique())

1848

In [9]:
df = df_tasks.merge(df_endpoints, on="endpoint_uuid")

In [25]:
df['total_time'] = df['result_received'] - df['received']

In [29]:
df['execution_time'] = df['execution_end'] - df['execution_start'] + df['waiting_for_nodes'] + df['waiting_for_launch']

In [ ]:
df['execution_time']

,task_uuid,function_uuid,endpoint_uuid,anonymized_user_uuid,argument_size,received,waiting_for_nodes,waiting_for_launch,execution_start,execution_end,result_received,endpoint_type,endpoint_version,total_time,execution_time
0,0ebb4c18-5d2c-4804-4329-17725d94788d,fef43cc0-a26a-b13f-e956-3455b3d24a41,651538d8-3fc4-98d6-c6a4-f89ecadd2544,def8a1a7-9bc1-e274-1213-3d6cb366d6e9,659.0,1.685553e+18,1.685553e+18,1.685553e+18,1.685553e+18,1.685553e+18,1.685553e+18,LocalProvider,2.0.0,9.981158e+07,3.371105e+18
1,7162505b-ca05-99ab-6cab-66b484448980,c6e65d92-f474-2222-cba7-36d0c3b558c8,57699a1f-f727-b5ef-28db-afaffeb0cb4d,e9abae78-6295-f7c7-17de-fc5f58818a2b,6054.0,NaN,1.684329e+18,1.684329e+18,1.684329e+18,1.684329e+18,1.684329e+18,CobaltProvider,2.0.1,NaN,3.368657e+18
2,fd4004eb-eb9c-d3d6-b718-93cb1c91c6d9,f9fb1939-d0e5-bb44-719b-1fca97a34a8f,9b1d9849-dd78-51bb-cb47-c48ebc5ef9c9,89f2c306-4c36-ffed-2553-e86692f055c3,46.0,1.686630e+18,1.686630e+18,1.686630e+18,1.686630e+18,1.686630e+18,1.686630e+18,LocalProvider,2.1.0,6.705731e+09,3.373259e+18
3,2a1e96f6-7999-b066-fc7b-e6adf8567031,eb1a35bc-eb3a-a4dd-c905-82823f30677d,9b1d9849-dd78-51bb-cb47-c48ebc5ef9c9,89f2c306-4c36-ffed-2553-e86692f055c3,46.0,1.686687e+18,1.686687e+18,1.686687e+18,1.686687e+18,1.686687e+18,1.686687e+18,LocalProvider,2.1.0,6.464767e+09,3.373375e+18
4,7ee1af85-bec6-50af-50d9-0c9dfbdabcc5,b4c9f870-b439-866c-79ac-abdf5ac4b9a2,57699a1f-f727-b5ef-28db-afaffeb0cb4d,e9abae78-6295-f7c7-17de-fc5f58818a2b,11433.0,1.684338e+18,1.684338e+18,1.684338e+18,1.684338e+18,1.684338e+18,1.684338e+18,CobaltProvider,2.0.1,4.004255e+08,3.368676e+18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2121467,39821951-0bba-d943-4453-93f2a99868aa,82f88f19-acd6-eca1-26ba-69282730b3e0,9e9628e2-f3b2-58cc-98ab-dcef2341e1c8,d3ea41e9-5a2a-47ba-9ea4-1d404f39baad,12223.0,NaN,1.682535e+18,1.682535e+18,1.682535e+18,1.682535e+18,1.682535e+18,LocalProvider,2.1.0a1,NaN,3.365069e+18
2121468,9a888468-ac24-1097-2eed-6e1c3c01906f,3e959bd1-f7a1-c559-981a-a54563bb1b54,9e9628e2-f3b2-58cc-98ab-dcef2341e1c8,d3ea41e9-5a2a-47ba-9ea4-1d404f39baad,196092.0,1.682534e+18,1.682534e+18,1.682534e+18,1.682534e+18,1.682534e+18,1.682534e+18,LocalProvider,2.1.0a1,7.224264e+08,3.365069e+18
2121469,3c1578b8-2967-8a1b-8dc8-67e879060540,07cbe97e-f170-b6c2-c090-b924eb8e3c0a,9e9628e2-f3b2-58cc-98ab-dcef2341e1c8,d3ea41e9-5a2a-47ba-9ea4-1d404f39baad,50.0,NaN,1.682436e+18,1.682436e+18,1.682436e+18,1.682436e+18,1.682436e+18,LocalProvider,2.1.0a1,NaN,3.364872e+18
2121470,9901ca42-4dc3-490b-5670-90012a8ac761,d491925e-e99e-fa6d-5c1f-70aad3bceb9f,fc1d7a40-6293-758c-2158-b7986a2089d6,d7524c22-4d1f-adba-a84b-ad7fb761b9a4,62.0,1.676524e+18,1.676524e+18,1.676524e+18,1.676524e+18,1.676524e+18,1.676524e+18,LocalProvider,2.0.1,2.770294e+08,3.353049e+18
2121471,a0599a21-6668-dd5b-273d-857917b1e8fe,4a103d77-0aec-94aa-c6e3-caa0366d9ab5,c190cd2b-4574-26ed-8e1d-0c5dc84bb11f,23452a38-0dfb-233f-dde3-443d0012cc40,NaN,1.671217e+18,NaN,NaN,NaN,NaN,1.671228e+18,LocalProvider,1.0.10,1.164527e+13,NaN

In [46]:
df.drop(columns=['received','waiting_for_nodes','waiting_for_launch','execution_start','execution_end','result_received'])

,task_uuid,function_uuid,endpoint_uuid,anonymized_user_uuid,argument_size,total_time,function_body_uuid,loc,cyc_complexity,num_of_imports
0,0ebb4c18-5d2c-4804-4329-17725d94788d,fef43cc0-a26a-b13f-e956-3455b3d24a41,651538d8-3fc4-98d6-c6a4-f89ecadd2544,def8a1a7-9bc1-e274-1213-3d6cb366d6e9,659.0,9.981158e+07,1627f3ca-0405-4404-4dbc-bd387425aa38,3.0,1.0,0.0
1,7162505b-ca05-99ab-6cab-66b484448980,c6e65d92-f474-2222-cba7-36d0c3b558c8,57699a1f-f727-b5ef-28db-afaffeb0cb4d,e9abae78-6295-f7c7-17de-fc5f58818a2b,6054.0,NaN,44c9883f-b632-30cd-2a0e-999ff52f40c5,NaN,NaN,NaN
2,fd4004eb-eb9c-d3d6-b718-93cb1c91c6d9,f9fb1939-d0e5-bb44-719b-1fca97a34a8f,9b1d9849-dd78-51bb-cb47-c48ebc5ef9c9,89f2c306-4c36-ffed-2553-e86692f055c3,46.0,6.705731e+09,212857ad-49e0-4379-edfe-d2b5b15d4009,2.0,1.0,0.0
3,2a1e96f6-7999-b066-fc7b-e6adf8567031,eb1a35bc-eb3a-a4dd-c905-82823f30677d,9b1d9849-dd78-51bb-cb47-c48ebc5ef9c9,89f2c306-4c36-ffed-2553-e86692f055c3,46.0,6.464767e+09,212857ad-49e0-4379-edfe-d2b5b15d4009,2.0,1.0,0.0
4,7ee1af85-bec6-50af-50d9-0c9dfbdabcc5,b4c9f870-b439-866c-79ac-abdf5ac4b9a2,57699a1f-f727-b5ef-28db-afaffeb0cb4d,e9abae78-6295-f7c7-17de-fc5f58818a2b,11433.0,4.004255e+08,44c9883f-b632-30cd-2a0e-999ff52f40c5,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2121467,39821951-0bba-d943-4453-93f2a99868aa,82f88f19-acd6-eca1-26ba-69282730b3e0,9e9628e2-f3b2-58cc-98ab-dcef2341e1c8,d3ea41e9-5a2a-47ba-9ea4-1d404f39baad,12223.0,NaN,f9d73689-05ea-1d56-10bb-a7e88c054bbe,20.0,6.0,1.0
2121468,9a888468-ac24-1097-2eed-6e1c3c01906f,3e959bd1-f7a1-c559-981a-a54563bb1b54,9e9628e2-f3b2-58cc-98ab-dcef2341e1c8,d3ea41e9-5a2a-47ba-9ea4-1d404f39baad,196092.0,7.224264e+08,673b093c-7b0d-63dc-2fd3-0473efd791bb,13.0,4.0,1.0
2121469,3c1578b8-2967-8a1b-8dc8-67e879060540,07cbe97e-f170-b6c2-c090-b924eb8e3c0a,9e9628e2-f3b2-58cc-98ab-dcef2341e1c8,d3ea41e9-5a2a-47ba-9ea4-1d404f39baad,50.0,NaN,d7616277-b745-598d-95aa-b51108b3d9c5,2.0,1.0,0.0
2121470,9901ca42-4dc3-490b-5670-90012a8ac761,d491925e-e99e-fa6d-5c1f-70aad3bceb9f,fc1d7a40-6293-758c-2158-b7986a2089d6,d7524c22-4d1f-adba-a84b-ad7fb761b9a4,62.0,2.770294e+08,1cd2079c-72a4-089e-9652-2ca5f5f9ec42,54.0,10.0,1.0
2121471,a0599a21-6668-dd5b-273d-857917b1e8fe,4a103d77-0aec-94aa-c6e3-caa0366d9ab5,c190cd2b-4574-26ed-8e1d-0c5dc84bb11f,23452a38-0dfb-233f-dde3-443d0012cc40,NaN,1.164527e+13,c8cd99a7-dedb-840a-7813-dd872c16b36f,38.0,2.0,4.0

In [62]:
df = df.merge(df_endpoints, on="endpoint_uuid")

In [70]:
len(df)

2121472

In [7]:
df_functions

,function_uuid,function_body_uuid,loc,cyc_complexity,num_of_imports
0,6f761b2f-b776-b1e2-ddeb-9ec002e484e4,1cd2079c-72a4-089e-9652-2ca5f5f9ec42,54.0,10.0,1.0
1,fef43cc0-a26a-b13f-e956-3455b3d24a41,1627f3ca-0405-4404-4dbc-bd387425aa38,3.0,1.0,0.0
2,fdecf895-cfa5-a1e8-569e-f631c60965e2,1cd2079c-72a4-089e-9652-2ca5f5f9ec42,54.0,10.0,1.0
3,cacfa841-7210-e4e8-6508-5c025381a5bd,1cd2079c-72a4-089e-9652-2ca5f5f9ec42,54.0,10.0,1.0
4,14babd79-1054-93e1-c559-713fda85fb20,44c9883f-b632-30cd-2a0e-999ff52f40c5,NaN,NaN,NaN
...,...,...,...,...,...
277381,cb97304f-5dff-e934-44d8-42144263ee2c,7502ac21-fb80-6404-5e59-7977d4b5ef7f,5.0,1.0,2.0
277382,c00910a2-0320-d35d-35c7-d3776d6b3dee,157d4850-88b8-a2bd-0914-b055d6c245fd,18.0,4.0,3.0
277383,694daf13-bf49-7aff-4d2d-0bc5e62a798a,9047fa88-a231-8867-17d1-38b787d18751,15.0,3.0,2.0
277384,5ceca064-e135-1a1f-c0e4-9ea9dab4fbd4,147e2ff0-73cb-e11d-3720-7d7a10f45f12,49.0,5.0,4.0
277385,1be0377a-ee57-a517-6319-4daad02cc1ea,9c71cc30-9211-41e5-fc52-281337604086,10.0,1.0,2.0

In [6]:
df_tasks

,task_uuid,function_uuid,endpoint_uuid,anonymized_user_uuid,argument_size,received,waiting_for_nodes,waiting_for_launch,execution_start,execution_end,result_received
0,0ebb4c18-5d2c-4804-4329-17725d94788d,fef43cc0-a26a-b13f-e956-3455b3d24a41,651538d8-3fc4-98d6-c6a4-f89ecadd2544,def8a1a7-9bc1-e274-1213-3d6cb366d6e9,659.0,1.685553e+18,1.685553e+18,1.685553e+18,1.685553e+18,1.685553e+18,1.685553e+18
1,7162505b-ca05-99ab-6cab-66b484448980,c6e65d92-f474-2222-cba7-36d0c3b558c8,57699a1f-f727-b5ef-28db-afaffeb0cb4d,e9abae78-6295-f7c7-17de-fc5f58818a2b,6054.0,NaN,1.684329e+18,1.684329e+18,1.684329e+18,1.684329e+18,1.684329e+18
2,fd4004eb-eb9c-d3d6-b718-93cb1c91c6d9,f9fb1939-d0e5-bb44-719b-1fca97a34a8f,9b1d9849-dd78-51bb-cb47-c48ebc5ef9c9,89f2c306-4c36-ffed-2553-e86692f055c3,46.0,1.686630e+18,1.686630e+18,1.686630e+18,1.686630e+18,1.686630e+18,1.686630e+18
3,2a1e96f6-7999-b066-fc7b-e6adf8567031,eb1a35bc-eb3a-a4dd-c905-82823f30677d,9b1d9849-dd78-51bb-cb47-c48ebc5ef9c9,89f2c306-4c36-ffed-2553-e86692f055c3,46.0,1.686687e+18,1.686687e+18,1.686687e+18,1.686687e+18,1.686687e+18,1.686687e+18
4,7ee1af85-bec6-50af-50d9-0c9dfbdabcc5,b4c9f870-b439-866c-79ac-abdf5ac4b9a2,57699a1f-f727-b5ef-28db-afaffeb0cb4d,e9abae78-6295-f7c7-17de-fc5f58818a2b,11433.0,1.684338e+18,1.684338e+18,1.684338e+18,1.684338e+18,1.684338e+18,1.684338e+18
...,...,...,...,...,...,...,...,...,...,...,...
2121467,39821951-0bba-d943-4453-93f2a99868aa,82f88f19-acd6-eca1-26ba-69282730b3e0,9e9628e2-f3b2-58cc-98ab-dcef2341e1c8,d3ea41e9-5a2a-47ba-9ea4-1d404f39baad,12223.0,NaN,1.682535e+18,1.682535e+18,1.682535e+18,1.682535e+18,1.682535e+18
2121468,9a888468-ac24-1097-2eed-6e1c3c01906f,3e959bd1-f7a1-c559-981a-a54563bb1b54,9e9628e2-f3b2-58cc-98ab-dcef2341e1c8,d3ea41e9-5a2a-47ba-9ea4-1d404f39baad,196092.0,1.682534e+18,1.682534e+18,1.682534e+18,1.682534e+18,1.682534e+18,1.682534e+18
2121469,3c1578b8-2967-8a1b-8dc8-67e879060540,07cbe97e-f170-b6c2-c090-b924eb8e3c0a,9e9628e2-f3b2-58cc-98ab-dcef2341e1c8,d3ea41e9-5a2a-47ba-9ea4-1d404f39baad,50.0,NaN,1.682436e+18,1.682436e+18,1.682436e+18,1.682436e+18,1.682436e+18
2121470,9901ca42-4dc3-490b-5670-90012a8ac761,d491925e-e99e-fa6d-5c1f-70aad3bceb9f,fc1d7a40-6293-758c-2158-b7986a2089d6,d7524c22-4d1f-adba-a84b-ad7fb761b9a4,62.0,1.676524e+18,1.676524e+18,1.676524e+18,1.676524e+18,1.676524e+18,1.676524e+18
2121471,a0599a21-6668-dd5b-273d-857917b1e8fe,4a103d77-0aec-94aa-c6e3-caa0366d9ab5,c190cd2b-4574-26ed-8e1d-0c5dc84bb11f,23452a38-0dfb-233f-dde3-443d0012cc40,NaN,1.671217e+18,NaN,NaN,NaN,NaN,1.671228e+18

In [47]:
print(df.columns.tolist())

['task_uuid', 'function_uuid', 'endpoint_uuid', 'anonymized_user_uuid', 'argument_size', 'received', 'waiting_for_nodes', 'waiting_for_launch', 'execution_start', 'execution_end', 'result_received', 'total_time', 'function_body_uuid', 'loc', 'cyc_complexity', 'num_of_imports']

In [51]:
df.isnull().sum()

task_uuid                    0
function_uuid                0
endpoint_uuid                0
anonymized_user_uuid         0
argument_size           245567
received                394993
waiting_for_nodes       268297
waiting_for_launch      289574
execution_start         244541
execution_end           244532
result_received          95725
total_time              464319
function_body_uuid           0
loc                     267368
cyc_complexity          267368
num_of_imports          267368
dtype: int64

In [50]:
df_clean = df.dropna(subset=['total_time', 'argument_size', 'loc', 'cyc_complexity', 'num_of_imports'])
print(f"Original df shape: {df.shape}")
print(f"Clean df shape: {df_clean.shape}")

Original df shape: (2121472, 16)
Clean df shape: (1370029, 16)

In [71]:
df_clean

,task_uuid,function_uuid,endpoint_uuid,anonymized_user_uuid,argument_size,received,waiting_for_nodes,waiting_for_launch,execution_start,execution_end,result_received,total_time,function_body_uuid,loc,cyc_complexity,num_of_imports
0,0ebb4c18-5d2c-4804-4329-17725d94788d,fef43cc0-a26a-b13f-e956-3455b3d24a41,651538d8-3fc4-98d6-c6a4-f89ecadd2544,def8a1a7-9bc1-e274-1213-3d6cb366d6e9,659.0,1.685553e+18,1.685553e+18,1.685553e+18,1.685553e+18,1.685553e+18,1.685553e+18,9.981158e+07,1627f3ca-0405-4404-4dbc-bd387425aa38,3.0,1.0,0.0
2,fd4004eb-eb9c-d3d6-b718-93cb1c91c6d9,f9fb1939-d0e5-bb44-719b-1fca97a34a8f,9b1d9849-dd78-51bb-cb47-c48ebc5ef9c9,89f2c306-4c36-ffed-2553-e86692f055c3,46.0,1.686630e+18,1.686630e+18,1.686630e+18,1.686630e+18,1.686630e+18,1.686630e+18,6.705731e+09,212857ad-49e0-4379-edfe-d2b5b15d4009,2.0,1.0,0.0
3,2a1e96f6-7999-b066-fc7b-e6adf8567031,eb1a35bc-eb3a-a4dd-c905-82823f30677d,9b1d9849-dd78-51bb-cb47-c48ebc5ef9c9,89f2c306-4c36-ffed-2553-e86692f055c3,46.0,1.686687e+18,1.686687e+18,1.686687e+18,1.686687e+18,1.686687e+18,1.686687e+18,6.464767e+09,212857ad-49e0-4379-edfe-d2b5b15d4009,2.0,1.0,0.0
5,ed0aa6c5-514d-45e3-703c-766279b08013,62681d2a-6c86-71dc-0e6c-9e8cd2bab13d,c84b6f08-caf5-11b0-de91-b0f7a2eec775,a7982e64-0077-bc42-12dc-d36ff6e9f672,46.0,1.683751e+18,1.683751e+18,1.683751e+18,1.683751e+18,1.683751e+18,1.683751e+18,4.021197e+07,eadd6eb5-96a8-bc08-2364-724db362de9c,2.0,1.0,0.0
6,b99704bb-f0d2-bda8-c84e-0c14c48fad9e,a6c00c2c-422b-b40f-6329-06042d94da1f,b1e0ed9d-91b9-8f22-1fb0-a9239b843d4d,55c7fbbb-5abc-2b27-5418-4d4b1920077f,62.0,1.688191e+18,1.688191e+18,1.688191e+18,1.688191e+18,1.688191e+18,1.688191e+18,2.527985e+08,1cd2079c-72a4-089e-9652-2ca5f5f9ec42,54.0,10.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2121464,abfda1d5-8754-d157-1c20-79842eb72ab5,f49355ef-d43f-be46-de3c-da086a5b757e,b0016b02-ef05-e6fa-659e-b6810fc9653b,b09e35c2-1a7e-68fc-671c-d709f4cc67b9,4672.0,1.676060e+18,1.676060e+18,1.676060e+18,1.676060e+18,1.676060e+18,1.676060e+18,6.412777e+09,f3a33766-f427-dd98-8b80-d921bceab0f9,21.0,4.0,3.0
2121465,d3596af5-0cd8-143e-abc4-6b3e6a975590,38254015-a721-adca-0be8-50e1863ed093,d93621ef-8dda-2aa1-93b2-48ecbf4d71e6,d7524c22-4d1f-adba-a84b-ad7fb761b9a4,62.0,1.670390e+18,NaN,NaN,NaN,NaN,1.670390e+18,2.718372e+08,1cd2079c-72a4-089e-9652-2ca5f5f9ec42,54.0,10.0,1.0
2121466,cf2d1606-4b33-09cb-ef13-ddd84511908a,48c9f356-6506-90bc-f562-48a693ee8e51,b1e0ed9d-91b9-8f22-1fb0-a9239b843d4d,55c7fbbb-5abc-2b27-5418-4d4b1920077f,78.0,1.677274e+18,1.677274e+18,1.677274e+18,1.677274e+18,1.677274e+18,1.677274e+18,2.061079e+09,1cd2079c-72a4-089e-9652-2ca5f5f9ec42,54.0,10.0,1.0
2121468,9a888468-ac24-1097-2eed-6e1c3c01906f,3e959bd1-f7a1-c559-981a-a54563bb1b54,9e9628e2-f3b2-58cc-98ab-dcef2341e1c8,d3ea41e9-5a2a-47ba-9ea4-1d404f39baad,196092.0,1.682534e+18,1.682534e+18,1.682534e+18,1.682534e+18,1.682534e+18,1.682534e+18,7.224264e+08,673b093c-7b0d-63dc-2fd3-0473efd791bb,13.0,4.0,1.0
2121470,9901ca42-4dc3-490b-5670-90012a8ac761,d491925e-e99e-fa6d-5c1f-70aad3bceb9f,fc1d7a40-6293-758c-2158-b7986a2089d6,d7524c22-4d1f-adba-a84b-ad7fb761b9a4,62.0,1.676524e+18,1.676524e+18,1.676524e+18,1.676524e+18,1.676524e+18,1.676524e+18,2.770294e+08,1cd2079c-72a4-089e-9652-2ca5f5f9ec42,54.0,10.0,1.0

In [52]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Define features and target
X = df_clean[['argument_size', 'loc', 'cyc_complexity', 'num_of_imports']]
y = df_clean['total_time']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and fit the linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Print the coefficients
print("Coefficients:")
for feature, coef in zip(X.columns, model.coef_):
    print(f"{feature}: {coef}")
print(f"Intercept: {model.intercept_}")

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

Coefficients:
argument_size: -126927.68857469922
loc: -1071975609.1480755
cyc_complexity: -180666959980.57852
num_of_imports: -75931151553.27895
Intercept: 1861807727195.183
Mean Squared Error: 2.5593403346353597e+26
R-squared: 0.0024055340658805102

In [57]:
from sklearn.ensemble import RandomForestRegressor

# Create and fit a Random Forest model (more complex)
rf_model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
rf_model.fit(X_train, y_train)

# Make predictions
rf_y_pred = rf_model.predict(X_test)

# Evaluate the Random Forest model
rf_mse = mean_squared_error(y_test, rf_y_pred)
rf_r2 = r2_score(y_test, rf_y_pred)
print("Random Forest Model:")
print(f"Mean Squared Error: {rf_mse}")
print(f"R-squared: {rf_r2}")

# Feature importances
print("\nFeature Importances:")
for feature, imp in zip(X.columns, rf_model.feature_importances_):
    print(f"{feature}: {imp}")

Random Forest Model:
Mean Squared Error: 2.3576301310967027e+26
R-squared: 0.0810293028743686

Feature Importances:
argument_size: 0.28717769637173396
loc: 0.7006881641538117
cyc_complexity: 0.001990715100467211
num_of_imports: 0.010143424373987138

In [58]:
from sklearn.model_selection import RandomizedSearchCV

# Define parameter distribution for Random Forest
param_dist = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt', 'log2']
}

# Create Random Forest model
rf = RandomForestRegressor(random_state=42)

# Perform Randomized Search with Cross-Validation
random_search = RandomizedSearchCV(
    rf, param_dist, n_iter=20, cv=3, scoring='r2', n_jobs=-1, random_state=42, verbose=1
)
random_search.fit(X_train, y_train)

# Best parameters and score
print("Best Parameters:", random_search.best_params_)
print("Best CV R-squared:", random_search.best_score_)

# Evaluate best model on test set
best_rf_model = random_search.best_estimator_
best_rf_y_pred = best_rf_model.predict(X_test)
best_rf_mse = mean_squared_error(y_test, best_rf_y_pred)
best_rf_r2 = r2_score(y_test, best_rf_y_pred)
print(f"Test MSE: {best_rf_mse}")
print(f"Test R-squared: {best_rf_r2}")

Fitting 3 folds for each of 20 candidates, totalling 60 fits

/Users/pcturnes/Documents/Projects/.conda/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:516: FitFailedWarning:
24 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/pcturnes/Documents/Projects/.conda/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/pcturnes/Documents/Projects/.conda/lib/python3.11/site-packages/sklearn/base.py", line 1356, in wrapper
    estimator._validate_params()
  File "/Users/pcturnes/Documents/Projects/.conda/lib/python3.11/site-packages/sklearn/base.py", line 469, in _validate_params
    validate_parameter_constraints(
  File "/Users/pcturnes/Documents/Projects/.conda/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
9 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/pcturnes/Documents/Projects/.conda/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/pcturnes/Documents/Projects/.conda/lib/python3.11/site-packages/sklearn/base.py", line 1356, in wrapper
    estimator._validate_params()
  File "/Users/pcturnes/Documents/Projects/.conda/lib/python3.11/site-packages/sklearn/base.py", line 469, in _validate_params
    validate_parameter_constraints(
  File "/Users/pcturnes/Documents/Projects/.conda/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/Users/pcturnes/Documents/Projects/.conda/lib/python3.11/site-packages/sklearn/model_selection/_search.py:1135: UserWarning: One or more of the test scores are non-finite: [0.07750774 0.07745802 0.07736626        nan        nan 0.07756861
 0.077533   0.07757248        nan 0.07747969        nan        nan
 0.07753717 0.0774902         nan 0.0774467  0.07760497 0.07746543
        nan        nan]
  warnings.warn(

Best Parameters: {'n_estimators': 200, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'max_depth': 30}
Best CV R-squared: 0.07760497453453814
Test MSE: 2.3585060419307765e+26
Test R-squared: 0.08068788528761828

In [59]:
from sklearn.linear_model import Ridge, Lasso
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
import pandas as pd

# List of models to try
models = {
    'Linear Regression': LinearRegression(),
    'Ridge Regression': Ridge(alpha=1.0),
    'Lasso Regression': Lasso(alpha=0.1),
    'Random Forest': RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1),
    'Gradient Boosting': GradientBoostingRegressor(n_estimators=100, random_state=42),
    'K-Neighbors Regressor': KNeighborsRegressor(n_neighbors=5)
}

# Note: SVR is commented out as it may be too slow for large datasets
# 'Support Vector Regressor': SVR(kernel='rbf')

results = []

for name, model in models.items():
    print(f"Fitting {name}...")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    results.append({'Model': name, 'MSE': mse, 'R2': r2})
    print(f"{name}: MSE={mse:.2e}, R2={r2:.4f}")

# Create a DataFrame for comparison
results_df = pd.DataFrame(results)
print("\nModel Comparison:")
print(results_df.sort_values(by='R2', ascending=False))

Fitting Linear Regression...
Linear Regression: MSE=2.56e+26, R2=0.0024
Fitting Ridge Regression...
Ridge Regression: MSE=2.56e+26, R2=0.0024
Fitting Lasso Regression...
Lasso Regression: MSE=2.56e+26, R2=0.0024
Fitting Random Forest...
Random Forest: MSE=2.36e+26, R2=0.0810
Fitting Gradient Boosting...
Gradient Boosting: MSE=2.36e+26, R2=0.0791
Fitting K-Neighbors Regressor...
K-Neighbors Regressor: MSE=2.59e+26, R2=-0.0085

Model Comparison:
                   Model           MSE        R2
3          Random Forest  2.357630e+26  0.081029
4      Gradient Boosting  2.362675e+26  0.079063
0      Linear Regression  2.559340e+26  0.002406
2       Lasso Regression  2.559340e+26  0.002406
1       Ridge Regression  2.559340e+26  0.002406
5  K-Neighbors Regressor  2.587446e+26 -0.008550